services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped

  server:
    build:
      context: ./server
    restart: unless-stopped

  client:
    build:
      context: ./client
    restart: unless-stopped
